### ISSUE TITLE
Windows: Unicode characters break Clipboard

### ISSUE THREAD

**Issue by RuiNtD** [Slackadays/Clipboard#157]
**Describe the bug**
Unicode characters cause many functions of Clipboard to break.

**To Reproduce**
1. `cb -c amog cp ඞ`
2. `cb status`
3. Observe CP locking up as not finishing.

**Expected behavior**
`cb status` runs as expected

**Screenshots**

**Version**
CB 0.8.1 downloaded from Scoop on Windows 11

**Questionnaire**
Check these boxes to see if your issue is valid or not.
- [X] If I compiled CB, then any errors that may be present don't mention "LTO error" (this is sadly a bug with the compiler, not Clipboard)
- [X] If I compiled CB, then any errors that may be present don't mention "XYZ has not been defined in namespace std" (this sadly means you need a compiler with C++20 support, so upgrade first)
- [ ] I check all these boxes without reading them
- [ ] I think bachata is the best music
- [X] I'm using the latest commit/release (we only support the latest)
- [X] If I downloaded CB from GitHub Actions or with the install script, any errors that may be present don't mention "GLIBC XYZ not found" (your system is sadly too outdated for CB, so upgrade it)

**Additional context**
This also results in bad escaping for the JSON outputs, but that's covered in #152

**Comment by Slackadays** [comment]
fixed in https://github.com/Slackadays/Clipboard/commit/8fbfad477c68863a342d87ffb6be2a07722fd49e, this wasn't actually a unicode but rather a file locking bug

**Comment by RuiNtD** [comment]
Hello. I'm actually still seeing the issue in 5606f1ba3d3b3a52658b9138dffb96db1b9f1182. Stalls when I run `cb status`

**Comment by Slackadays** [comment]
Try removing the lock file manually by running `cb info` and go into the folder where the clipboard is, then `metadata`, then `lock`. I had to do this to get the fix working on my side

**Comment by RuiNtD** [comment]
That worked! Thanks.
